[assembly: System.Reflection.AssemblyAlgorithmId(System.Configuration.Assemblies.AssemblyHashAlgorithm.SHA256)]
[assembly: System.Reflection.AssemblyCompany("RandomiaGaming")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2021 RandomiaGaming")]
//[assembly: AssemblyCulture(null)]
[assembly: System.Reflection.AssemblyDefaultAlias("SharpShell")]
[assembly: System.Reflection.AssemblyDescription("SharpShell is an open source utility designed to help you automate simple tasks through the use of a customizable and expandable set of functions which can be stitched together to create scripts and commands which preform specific tasks.")]
[assembly: System.Reflection.AssemblyFileVersion("1.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.1.0")]
[assembly: System.Reflection.AssemblyProduct("SharpShell")]
[assembly: System.Reflection.AssemblyTitle("SharpShell")]
[assembly: System.Reflection.AssemblyTrademark("Trademark 2021 RandomiaGaming")]
[assembly: System.Reflection.AssemblyVersion("1.1.0")]